In [1]:
import pandas as pd
import numpy as np

In [2]:
dim_course = pd.read_parquet('../data/bronze/parquet/dim_course.parquet')
dim_district = pd.read_parquet('../data/bronze/parquet/dim_district.parquet')
dim_university = pd.read_parquet('../data/bronze/parquet/dim_university.parquet')
dim_year = pd.read_parquet('../data/bronze/parquet/dim_year.parquet')
fact_cutoffs = pd.read_parquet('../data/bronze/parquet/fact_cutoffs.parquet')

In [3]:
# create dataframes for each file

course_df = pd.DataFrame(dim_course)
district_df = pd.DataFrame(dim_district)
university_df = pd.DataFrame(dim_university)
year_df = pd.DataFrame(dim_year)
fact_cutoffs_df = pd.DataFrame(fact_cutoffs)

In [4]:
course_df.head()

          CourseID                                     CourseName
0  COURSE_D5E20A1F                       AGRI BUSINESS MANAGEMENT
1  COURSE_6FB49258  AGRICULTURAL RESOURCE MANAGEMENT & TECHNOLOGY
2  COURSE_5EA0149E           AGRICULTURAL TECHNOLOGY & MANAGEMENT
3  COURSE_4173EF9E                                    AGRICULTURE
4  COURSE_E2281A76                                 ANIMAL SCIENCE

In [5]:
district_df.head()

          DistrictID DistrictName
0  DISTRICT_80F4B83B      COLOMBO
1  DISTRICT_40903503      GAMPAHA
2  DISTRICT_656E1CE3     KALUTARA
3  DISTRICT_A17237FA       MATALE
4  DISTRICT_3680DD41        KANDY

In [6]:
university_df.head()

          UniversityID                           UniversityName
0  UNIVERSITY_9536C93C  Eastern University - Trincomalee Campus
1  UNIVERSITY_E403C90A            Eastern University, Sri Lanka
2  UNIVERSITY_00B29E70         Rajarata University of Sri Lanka
3  UNIVERSITY_0D262C4B          Ramanathan Academy of Fine Arts
4  UNIVERSITY_CA0DA06F     Sabaragamuwa University of Sri Lanka

In [7]:
# inspectiong unique universities

print("Unique Universities: \n", university_df['UniversityName'].unique())

Unique Universities:
 <ArrowStringArray>
[                                 'Eastern University - Trincomalee Campus',
                                            'Eastern University, Sri Lanka',
                                         'Rajarata University of Sri Lanka',
                                          'Ramanathan Academy of Fine Arts',
                                     'Sabaragamuwa University of Sri Lanka',
                                    'South Eastern University of Sri Lanka',
                         'Swami Vipulananda Institute of Aesthetic Studies',
 'The Gampaha Wickramarachchi University of Indigenous Medicine, Sri Lanka',
                                                    'University of Colombo',
                                 'University of Colombo - Sri Palee Campus',
                                'University of Colombo School of Computing',
                                                     'University of Jaffna',
                                   'University of Jaffna - Vavuniya Campus',
                                                   'University of Kelaniya',
                                                   'University of Moratuwa',
                                                 'University of Peradeniya',
                                                     'University of Ruhuna',
                                        'University of Sri Jayewardenepura',
                               'University of the Visual & Performing Arts',
                                     'Uva Wellassa University of Sri Lanka',
                                          'Wayamba University of Sri Lanka',
                                        'University of Vavuniya, Sri Lanka']
Length: 22, dtype: str

In [8]:
year_df.head()

           YearID AcademicYear  ExamYear PublicationDate
0  YEAR_2018_2019    2018/2019      2018      2019-07-31
1  YEAR_2019_2020    2019/2020      2019      2020-07-31
2  YEAR_2020_2021    2020/2021      2020      2021-07-31
3  YEAR_2021_2022    2021/2022      2021      2022-07-31
4  YEAR_2022_2023    2022/2023      2022      2023-07-31

In [11]:
fact_cutoffs_df.tail()

,AcademicYear,ExamYear,PublicationDate,CourseID,CourseName,UniversityID,UniversityName,DistrictID,DistrictName,CutoffZ,CutoffStatus,AllIslandMerit,AptitudeTest,Page,SourceFile
49720,2025/2026,2025,2026-07-31,COURSE_172A9F57,VISUAL ARTS,UNIVERSITY_C56AA792,University of the Visual & Performing Arts,DISTRICT_7CD0BD98,POLONNARUWA,1.2344,AVAILABLE,False,True,10,COP_2025_2026.pdf
49721,2025/2026,2025,2026-07-31,COURSE_172A9F57,VISUAL ARTS,UNIVERSITY_C56AA792,University of the Visual & Performing Arts,DISTRICT_D43D107C,PUTTALAM,0.8721,AVAILABLE,False,True,10,COP_2025_2026.pdf
49722,2025/2026,2025,2026-07-31,COURSE_172A9F57,VISUAL ARTS,UNIVERSITY_C56AA792,University of the Visual & Performing Arts,DISTRICT_790A4733,RATNAPURA,0.9713,AVAILABLE,False,True,10,COP_2025_2026.pdf
49723,2025/2026,2025,2026-07-31,COURSE_172A9F57,VISUAL ARTS,UNIVERSITY_C56AA792,University of the Visual & Performing Arts,DISTRICT_4ACFF824,TRINCOMALEE,NaN,NQC,False,True,10,COP_2025_2026.pdf
49724,2025/2026,2025,2026-07-31,COURSE_172A9F57,VISUAL ARTS,UNIVERSITY_C56AA792,University of the Visual & Performing Arts,DISTRICT_888B1DAB,VAVUNIYA,NaN,NQC,False,True,10,COP_2025_2026.pdf

In [10]:
# inspecting unique academic years

print("Unique Academic Years:", year_df['AcademicYear'].unique())
print("Unique Exam Years:", year_df['ExamYear'].unique())

Unique Academic Years: <ArrowStringArray>
['2018/2019', '2019/2020', '2020/2021', '2021/2022', '2022/2023', '2023/2024',
 '2024/2025', '2025/2026']
Length: 8, dtype: str
Unique Exam Years: [2018 2019 2020 2021 2022 2023 2024 2025]